#!/bin/bash
# start database

########################
# INSERT YOUR MAIL ACCOUNT HERE
##########################
 SMARTHOST_ADDRESS=mail.gmx.net
 SMARTHOST_PORT=465
 SMARTHOST_USER=some.mail.address
 SMARTHOST_PASSWORD=somepasswd
 SMARTHOST_ALIASES=*.mysmtp.com
 ################################
 


MYSQL_NAME="mysqlcontainer"
SMTP_NAME="smtphost"
# todo.. change this to random
MYSQL_ROOTPW="gwe12uhs"



MYSQL_DATADIR="/Volumes/UserData/Documents/Buchhaltung/simpleinvoices/mysqldata"
#SI_ROOT="/Volumes/UserData/Documents/Buchhaltung/simpleinvoices/"
SI_NAME="simpleinvoices"
PHPMYADMIN_NAME="phpmyadmin"
AUTOMYSQLBACKUP_NAME="automysql"
AUTOMYSQLBACKUP_DIR="/Volumes/UserData/Documents/Buchhaltung/backups/automysql"


# Start the Simpleinvoices Stack
startme() {
#make sure the data 
mkdir -p $MYSQL_DATADIR
mkdir -p $AUTOMYSQLBACKUP_DIR


#start the smtp host
docker run --name $SMTP_NAME -e SMARTHOST_ADDRESS=$SMARTHOST_ADDRESS -e SMARTHOST_PORT=$SMARTHOST_PORT -e SMARTHOST_USER=$SMARTHOST_USER -e SMARTHOST_PASSWORD=$SMARTHOST_PASSWORD -e SMARTHOST_ALIASES=$SMARTHOST_ALIASES -d namshi/smtp 



#start database
docker run -v $MYSQL_DATADIR:/var/lib/mysql --name $MYSQL_NAME -e MYSQL_ROOT_PASSWORD=$MYSQL_ROOTPW -d mysql:5.5

# start Docker apache-php with simpleinvoices
docker run --link $SMTP_NAME:smtp --link $MYSQL_NAME:mysql --name $SI_NAME -p 80:80 -d mposch/simpleinvoices 
 



# start phpmyadmin
docker run --name $PHPMYADMIN_NAME -d --link $MYSQL_NAME:db -p 8080:80 phpmyadmin/phpmyadmin
#start automysqlbackup
docker run --name $AUTOMYSQLBACKUP_NAME --link $MYSQL_NAME:mysql -v $AUTOMYSQLBACKUP_DIR:/backup -e DBHOST=mysql -e USERNAME=root -e PASSWORD=$MYSQL_ROOTPW -e DBNAMES=all -e CRON_SCHEDULE="0 0 * * *"  -d selim13/automysqlbackup

}

stopme() {
	docker stop $MYSQL_NAME
	docker stop $SI_NAME
	docker stop $PHPMYADMIN_NAME
	docker stop $AUTOMYSQLBACKUP_NAME
	docker stop $SMTP_NAME
	docker rm $MYSQL_NAME $SI_NAME $PHPMYADMIN_NAME $AUTOMYSQLBACKUP_NAME $SMTP_NAME
	
}
case "$1" in 
    start)   startme ;;
    stop)    stopme ;;
    restart) stopme; startme ;;
    *) echo "usage: $0 start|stop|restart" >&2
       exit 1
       ;;
esac

